# Generated by Django 3.2.7 on 2022-06-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='source',
            new_name='source_url',
        ),
    ]
