# Generated by Django 3.2.7 on 2022-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0002_rename_source_file_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
