# Generated by Django 3.2.7 on 2022-06-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0005_courses_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
