# Generated by Django 3.2.7 on 2022-06-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0006_auto_20220624_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='IncometAPI.courses'),
        ),
    ]
