# Generated by Django 3.2.7 on 2022-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0007_alter_rating_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='number_of_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='rating_number',
            field=models.IntegerField(null=True),
        ),
    ]
