# Generated by Django 3.2.7 on 2022-06-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IncometAPI', '0008_auto_20220625_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='News',
        ),
    ]
