# Generated by Django 3.2.7 on 2022-04-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='active',
            new_name='is_active',
        ),
    ]
