# Generated by Django 3.2.7 on 2022-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_rename_active_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
