# Generated by Django 3.2.7 on 2022-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20220429_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
