# Generated by Django 3.2.7 on 2022-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_auto_20220430_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
