# Generated by Django 3.2.7 on 2022-05-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_alter_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteril',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.batch')),
                ('trand_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.languages')),
            ],
        ),
    ]
